---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "react"
        versions: [">=18.2.0"]
      - dependency-name: "react-dom"
        versions: [">=18.2.0"]
      - dependency-name: "react-router"
        versions: [">=6.22.0"]
      - dependency-name: "react-router-dom"
        versions: [">=6.22.0"]
      - dependency-name: "purgecss"
        versions: [">=5.0.0"]
      - dependency-name: "vite"
        versions: [">=5.1.6"]
